# -*- coding: utf-8 -*-
"""streamlit run data_analysis_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ZQaIyFf63gZ7f3vfARDuMZ5JmcPm3-r
"""

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, mean_squared_error
from io import BytesIO

# --- ADVANCED FILTERING ---
def add_filtering_ui(df):
    st.sidebar.subheader("🔍 Advanced Filtering")
    filtered_df = df.copy()
    for col in df.select_dtypes(include=['object']).columns:
        options = df[col].unique().tolist()
        selected = st.sidebar.multiselect(f"Filter {col}", options, default=options)
        filtered_df = filtered_df[filtered_df[col].isin(selected)]
    for col in df.select_dtypes(include=[np.number]).columns:
        min_val, max_val = float(df[col].min()), float(df[col].max())
        range_val = st.sidebar.slider(f"Range for {col}", min_val, max_val, (min_val, max_val))
        filtered_df = filtered_df[df[col].between(*range_val)]
    return filtered_df

# --- EXPORT BUTTON ---
def download_button(df, label="Download CSV"):
    buffer = BytesIO()
    df.to_csv(buffer, index=False)
    buffer.seek(0)
    st.download_button(label=label, data=buffer, file_name="exported_data.csv", mime="text/csv")

# --- MODEL PREDICTION ---
def model_prediction_ui(df):
    st.markdown("<div class='section-header'>🤖 Model Prediction</div>", unsafe_allow_html=True)
    target = st.selectbox("Select target column", df.columns)
    task_type = "classification" if df[target].nunique() < 10 else "regression"
    X = df.drop(columns=[target]).select_dtypes(include=[np.number]).dropna()
    y = df[target].loc[X.index]
    if X.empty or y.isnull().any():
        st.warning("Insufficient numeric data or missing target values for modeling.")
        return

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
    if task_type == "classification":
        model = RandomForestClassifier()
        model.fit(X_train, y_train)
        preds = model.predict(X_test)
        st.success(f"Accuracy: {accuracy_score(y_test, preds):.2f}")
    else:
        model = RandomForestRegressor()
        model.fit(X_train, y_train)
        preds = model.predict(X_test)
        st.success(f"RMSE: {mean_squared_error(y_test, preds, squared=False):.2f}")

    full_preds = model.predict(X)
    df[f"Predicted_{target}"] = full_preds
    st.dataframe(df[[target, f"Predicted_{target}"]].head())
    download_button(df, label="Download Predictions")

# --- INSIGHT REPORT ---
def generate_interpretation(df):
    st.markdown("<div class='section-header'>📋 Summary Interpretation</div>", unsafe_allow_html=True)
    st.write(f"The dataset has **{df.shape[0]} rows** and **{df.shape[1]} columns**. It contains:")
    st.markdown("- 🔢 Numeric columns for statistical modeling")
    st.markdown("- 🧾 Categorical columns for grouping/filtering")
    st.markdown("- ⏱️ Possible datetime columns for time series trends")
    st.markdown("Key observations and visual insights were generated above to guide decision-making.")

# MAIN APP EXECUTION
if __name__ == "__main__":
    st.set_page_config(page_title="End-to-End Data Analysis", layout="wide")
    st.title("📊 End-to-End Data Analyzer")
    uploaded_file = st.file_uploader("Upload your dataset", type=["csv", "xlsx", "xls"])

    if uploaded_file:
        df = pd.read_csv(uploaded_file) if uploaded_file.name.endswith('.csv') else pd.read_excel(uploaded_file)
        df = add_filtering_ui(df)
        st.success(f"✅ Data loaded. Shape after filters: {df.shape}")
        st.subheader("👀 Data Preview")
        st.dataframe(df.head(), use_container_width=True)

        st.subheader("📌 Summary Statistics")
        st.dataframe(df.describe(include='all').T)

        st.subheader("📈 Visualizations")
        for col in df.select_dtypes(include=[np.number]).columns[:3]:
            st.line_chart(df[col], height=250)
            st.caption(f"Trend line of {col}")

        generate_interpretation(df)
        model_prediction_ui(df)
        download_button(df, label="Download Final Dataset")